package org.example.PSK.mybatis.model;

import lombok.Getter;
import lombok.Setter;
import org.example.PSK.entities.Vehicle;

import java.util.List;

public class Driver {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.PID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private Long pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private String surname;

    @Setter @Getter
    private List<Vehicle> vehicles;

    @Setter @Getter
    private List<Fare> fares;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.PID
     *
     * @return the value of PUBLIC.DRIVER.PID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.PID
     *
     * @param pid the value for PUBLIC.DRIVER.PID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.NAME
     *
     * @return the value of PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.NAME
     *
     * @param name the value for PUBLIC.DRIVER.NAME
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVER.SURNAME
     *
     * @return the value of PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVER.SURNAME
     *
     * @param surname the value for PUBLIC.DRIVER.SURNAME
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}