package org.example.PSK.mybatis.model;

import java.util.Date;

public class Fare {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FARE.ORDERID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private Long orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FARE.ENDLOCATION
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private String endlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FARE.ORDERTIMESTAMP
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private Date ordertimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FARE.STARTLOCATION
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private String startlocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FARE.DRIVER_PID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private Long driverPid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FARE.ORDERID
     *
     * @return the value of PUBLIC.FARE.ORDERID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FARE.ORDERID
     *
     * @param orderid the value for PUBLIC.FARE.ORDERID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FARE.ENDLOCATION
     *
     * @return the value of PUBLIC.FARE.ENDLOCATION
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public String getEndlocation() {
        return endlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FARE.ENDLOCATION
     *
     * @param endlocation the value for PUBLIC.FARE.ENDLOCATION
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setEndlocation(String endlocation) {
        this.endlocation = endlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FARE.ORDERTIMESTAMP
     *
     * @return the value of PUBLIC.FARE.ORDERTIMESTAMP
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public Date getOrdertimestamp() {
        return ordertimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FARE.ORDERTIMESTAMP
     *
     * @param ordertimestamp the value for PUBLIC.FARE.ORDERTIMESTAMP
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setOrdertimestamp(Date ordertimestamp) {
        this.ordertimestamp = ordertimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FARE.STARTLOCATION
     *
     * @return the value of PUBLIC.FARE.STARTLOCATION
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public String getStartlocation() {
        return startlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FARE.STARTLOCATION
     *
     * @param startlocation the value for PUBLIC.FARE.STARTLOCATION
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setStartlocation(String startlocation) {
        this.startlocation = startlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FARE.DRIVER_PID
     *
     * @return the value of PUBLIC.FARE.DRIVER_PID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public Long getDriverPid() {
        return driverPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FARE.DRIVER_PID
     *
     * @param driverPid the value for PUBLIC.FARE.DRIVER_PID
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setDriverPid(Long driverPid) {
        this.driverPid = driverPid;
    }
}