package org.example.PSK.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class Vehicle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VEHICLE.VIN
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private String vin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VEHICLE.MILEAGE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private Long mileage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.VEHICLE.STATUS
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    private String status;

    @Setter @Getter
    private List<Driver> drivers;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VEHICLE.VIN
     *
     * @return the value of PUBLIC.VEHICLE.VIN
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VEHICLE.VIN
     *
     * @param vin the value for PUBLIC.VEHICLE.VIN
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setVin(String vin) {
        this.vin = vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VEHICLE.MILEAGE
     *
     * @return the value of PUBLIC.VEHICLE.MILEAGE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public Long getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VEHICLE.MILEAGE
     *
     * @param mileage the value for PUBLIC.VEHICLE.MILEAGE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setMileage(Long mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.VEHICLE.STATUS
     *
     * @return the value of PUBLIC.VEHICLE.STATUS
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.VEHICLE.STATUS
     *
     * @param status the value for PUBLIC.VEHICLE.STATUS
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    public void setStatus(String status) {
        this.status = status;
    }
}