package org.example.PSK.mybatis.dao;

import java.util.List;
import org.example.PSK.mybatis.model.Fare;
import org.mybatis.cdi.Mapper;

@Mapper
public interface FareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FARE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    int deleteByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FARE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    int insert(Fare row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FARE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    Fare selectByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FARE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    List<Fare> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FARE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    int updateByPrimaryKey(Fare row);
}