package org.example.PSK.mybatis.dao;

import java.util.List;
import org.example.PSK.mybatis.model.Vehicle;
import org.mybatis.cdi.Mapper;

@Mapper
public interface VehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    int deleteByPrimaryKey(String vin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    int insert(Vehicle row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    Vehicle selectByPrimaryKey(String vin);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    List<Vehicle> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.VEHICLE
     *
     * @mbg.generated Sat Apr 27 19:47:12 EEST 2024
     */
    int updateByPrimaryKey(Vehicle row);
}